// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts_like.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countLikesForPost = `-- name: CountLikesForPost :one
SELECT COUNT(*)::BIGINT FROM post_likes WHERE post_id = $1
`

func (q *Queries) CountLikesForPost(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLikesForPost, postID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPostLike = `-- name: CreatePostLike :one
INSERT INTO
    post_likes (
        id,
        created_at,
        updated_at,
        post_id,
        user_id
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, created_at, updated_at, post_id, user_id
`

type CreatePostLikeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	PostID    uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (PostLike, error) {
	row := q.db.QueryRowContext(ctx, createPostLike,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PostID,
		arg.UserID,
	)
	var i PostLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}

const deletePostLike = `-- name: DeletePostLike :exec
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type DeletePostLikeParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) error {
	_, err := q.db.ExecContext(ctx, deletePostLike, arg.PostID, arg.UserID)
	return err
}

const getLikedPostsForUser = `-- name: GetLikedPostsForUser :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id, feeds.name AS feed_name
FROM post_likes
    JOIN posts ON post_likes.post_id = posts.id
    JOIN feeds ON posts.feed_id = feeds.id
WHERE
    post_likes.user_id = $1
ORDER BY post_likes.created_at DESC
`

type GetLikedPostsForUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
	FeedName    string
}

func (q *Queries) GetLikedPostsForUser(ctx context.Context, userID uuid.UUID) ([]GetLikedPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getLikedPostsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLikedPostsForUserRow
	for rows.Next() {
		var i GetLikedPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostLikeByPostAndUser = `-- name: GetPostLikeByPostAndUser :one
SELECT id, created_at, updated_at, post_id, user_id FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type GetPostLikeByPostAndUserParams struct {
	PostID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPostLikeByPostAndUser(ctx context.Context, arg GetPostLikeByPostAndUserParams) (PostLike, error) {
	row := q.db.QueryRowContext(ctx, getPostLikeByPostAndUser, arg.PostID, arg.UserID)
	var i PostLike
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}
